# Generated by Django 6.0.3 on 2026-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('jalan', 'Jalan'), ('sampah', 'Sampah'), ('lampu', 'Lampu Jalan'), ('air', 'Air'), ('lainnya', 'Lainnya')], max_length=50)),
                ('incident_date', models.DateField()),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
